networks:
  proxy:
    external: true
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  rustfs:
    <<: *logging-policy
    image: rustfs/rustfs:${rustfs_version:-latest}
    container_name: rustfs
    user: ${uid:-1000}:${gid:-1000}
    restart: unless-stopped
    command: --access-key ${default_access_key:?} --secret-key ${default_secret_key:?} /data
    networks:
      proxy:
    environment:
      RUSTFS_ACCESS_KEY: ${default_access_key:?}
      RUSTFS_SECRET_KEY: ${default_secret_key:?}
    volumes:
      - ${data:-.}/data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.rustfs.entryPoints: "https"
      traefik.http.routers.rustfs.middlewares: "localonly@file"
      traefik.http.routers.rustfs.rule: "Host(`rs.${domain}`)"
      traefik.http.routers.rustfs.service: "rustfs"
      traefik.http.services.rustfs.loadbalancer.server.url: "http://rustfs:9001"
      # S3 entrypoint
      traefik.http.routers.rustfs-s3.entryPoints: "https"
      traefik.http.routers.rustfs-s3.middlewares: "localonly@file"
      traefik.http.routers.rustfs-s3.rule: "Host(`r3.${domain}`)"
      traefik.http.routers.rustfs-s3.service: "rustfs-s3"
      traefik.http.services.rustfs-s3.loadbalancer.server.url: "http://rustfs:9000"
