networks:
  proxy:
    external: true
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  homeassistant:
    <<: *logging-policy
    image: ghcr.io/home-assistant/home-assistant:${homeassistant_version:-stable}
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    networks:
      proxy: null
    volumes:
      - ${data:-.}/homeassistant:/config # Local storage
      - /etc/localtime:/etc/localtime:ro # Timezone synchronization
      - /run/dbus:/run/dbus:ro # Bluetooth connection
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Zigbee radio controller
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.entryPoints: "https"
      traefik.http.routers.homeassistant.middlewares: "localonly@file"
      traefik.http.routers.homeassistant.rule: "Host(`ha.${domain}`)"
      traefik.http.services.homeassistant.loadbalancer.server.url: "http://homeassistant:8123"
