networks:
  proxy:
    external: true
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  homeassistant:
    <<: *logging-policy
    image: ghcr.io/home-assistant/home-assistant:${homeassistant_version:-stable}
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    networks:
      proxy: null
    volumes:
      - ${data:-.}/homeassistant:/config # Local storage
      - /etc/localtime:/etc/localtime:ro # Timezone synchronization
      - /run/dbus:/run/dbus:ro # Bluetooth connection
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Zigbee radio controller
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.entryPoints: "https"
      traefik.http.routers.homeassistant.middlewares: "localonly@file"
      traefik.http.routers.homeassistant.rule: "Host(`ha.${domain}`)"
      traefik.http.services.homeassistant.loadbalancer.server.url: "http://homeassistant:8123"
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:{zwave_version:-latest}
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      SESSION_SECRET: ${key:?change_me}
      TZ: ${timezone:-UTC}
    networks:
      - proxy
    devices:
      - '${device_id}:/dev/zwave'
    volumes:
      - ${data:-.}/zwave-config:/usr/src/app/store
    labels:
      traefik.enable: "true"
      traefik.http.routers.zwave.entryPoints: "https"
      traefik.http.routers.zwave.middlewares: "localonly@file"
      traefik.http.routers.zwave.rule: "Host(`zw.${domain}`)"
      traefik.http.services.zwave.loadbalancer.server.url: "http://zwave-js-ui:8091"