networks:
  proxy:
    external: true
  default:
x-common-settings: &common-settings
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  stdin_open: false
  tty: false
services:
  immich-server:
    <<: *common-settings
    image: ghcr.io/immich-app/immich-server:${immich_version:-release}
    container_name: immich_server
    cap_drop:
      - ALL
    depends_on:
      - database
      - immich-machine-learning
      - immich_keydb
    networks:
      proxy: null
      default: null
    healthcheck:
      disable: false
    environment:
      TZ: ${timezone:-UTC}
      DB_DATABASE_NAME: ${db_name:-immich}
      DB_PASSWORD: ${db_pass:?}
      DB_USERNAME: ${db_user:-immich}
      REDIS_HOSTNAME: immich_keydb
    volumes:
      - ${data:-.}/app:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.entryPoints: "https"
      traefik.http.routers.immich.middlewares: "localonly@file"
      traefik.http.routers.immich.rule: "Host(`im.${domain:?}`)"
      traefik.http.services.immich.loadbalancer.server.url: "http://immich_server:2283"
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${immich_version:-release}
    container_name: immich_machine_learning
    cap_drop:
      - ALL
    networks:
      default: null
    environment:
      TZ: ${timezone:-UTC}
      DB_DATABASE_NAME: ${db_name:-immich}
      DB_USERNAME: ${db_user:-immich}
      DB_PASSWORD: ${db_pass:?}
    volumes:
      - ${data:-.}/model-cache:/cache
    healthcheck:
      disable: false
  immich_keydb:
    <<: *common-settings
    image: eqalpha/keydb:${keydb_version:-latest}
    container_name: immich_keydb
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      default: null
    volumes:
      - ${data:-.}/keydb:/data
    healthcheck:
      test: redis-cli ping || exit 1
  database:
    <<: *common-settings
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    networks:
      default: null
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${db_name:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${db_pass:?}
      POSTGRES_USER: ${db_user:-immich}
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
