networks:
  proxy:
    external: true
  default:
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  immich-server:
    <<: *logging-policy
    image: ghcr.io/immich-app/immich-server:${immich_version:-release}
    container_name: immich_server
    restart: unless-stopped
    depends_on:
      - database
      - immich-machine-learning
      - immich_keydb
    networks:
      proxy: null
      default: null
    healthcheck:
      disable: false
    environment:
      TZ: ${timezone:-UTC}
      DB_DATABASE_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: ${db_pass:-postgres}
    volumes:
      - ${data:-.}/app:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.entryPoints: "https"
      traefik.http.routers.immich.middlewares: "localonly@file"
      traefik.http.routers.immich.rule: "Host(`im.${domain}`)"
      traefik.http.services.immich.loadbalancer.server.url: "http://immich_server:2283"
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${immich_version:-release}
    container_name: immich_machine_learning
    restart: unless-stopped
    networks:
      default: null
    environment:
      TZ: ${timezone:-UTC}
      DB_DATABASE_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: ${db_pass:-postgres}
    volumes:
      - ${data:-.}/model-cache:/cache
    healthcheck:
      disable: false
  immich_keydb:
    <<: *logging-policy
    image: eqalpha/keydb:${keydb_version:-latest}
    container_name: immich_keydb
    restart: unless-stopped
    networks:
      default: null
    volumes:
      - ${data:-.}/keydb:/data
    healthcheck:
      test: redis-cli ping || exit 1
  database:
    <<: *logging-policy
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    networks:
      default: null
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${db_pass:-postgres}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
