networks:
  default: null
  proxy:
    external: true
x-common-settings: &common-settings
  logging:
    driver: local
    options:
      compress: "true"
      max-file: "3"
      max-size: "10m"
  restart: unless-stopped
  security_opt:
    - no-new-privileges:true
  stdin_open: false
  tty: false
services:
  immich_postgres:
    <<: *common-settings
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    container_name: immich_postgres
    environment:
      POSTGRES_DB: ${db_name:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${db_pass:?}
      POSTGRES_USER: ${db_user:-immich}
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    labels:
      kuma.__docker:
    networks:
      default: null
    shm_size: 128mb
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
  immich_keydb:
    <<: *common-settings
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    container_name: immich_keydb
    healthcheck:
      test: redis-cli ping || exit 1
    image: eqalpha/keydb:${keydb_version:-latest}
    labels:
      kuma.__docker:
    networks:
      default: null
    volumes:
      - ${data:-.}/keydb:/data
  immich_machine_learning:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: immich_machine_learning
    environment:
      DB_DATABASE_NAME: ${db_name:-immich}
      DB_PASSWORD: ${db_pass:?}
      DB_USERNAME: ${db_user:-immich}
      TZ: ${timezone:-UTC}
    healthcheck:
      disable: false
    image: ghcr.io/immich-app/immich-machine-learning:${immich_version:-release}
    labels:
      kuma.__docker:
    networks:
      default: null
    volumes:
      - ${data:-.}/model-cache:/cache
  immich:
    <<: *common-settings
    cap_drop:
      - ALL
    container_name: immich
    depends_on:
      - immich_postgres
      - immich_keydb
      - immich_machine_learning
    environment:
      DB_DATABASE_NAME: ${db_name:-immich}
      DB_HOSTNAME: immich_postgres
      DB_PASSWORD: ${db_pass:?}
      DB_USERNAME: ${db_user:-immich}
      REDIS_HOSTNAME: immich_keydb
      TZ: ${timezone:-UTC}
    healthcheck:
      disable: false
    image: ghcr.io/immich-app/immich-server:${immich_version:-release}
    labels:
      kuma.__docker:
      kuma.__web: '"im.${domain:?}/auth/login"'
      traefik.enable: "true"
      traefik.http.routers.immich.entryPoints: "https"
      traefik.http.routers.immich.middlewares: "localonly@file"
      traefik.http.routers.immich.rule: "Host(`im.${domain:?}`)"
      traefik.http.services.immich.loadbalancer.server.url: "http://immich:2283"
    networks:
      proxy: null
      default: null
    volumes:
      - ${data:-.}/app:/data
      - /etc/localtime:/etc/localtime:ro
