networks:
  default: null
  proxy:
    external: true
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  gitea:
    <<: *logging-policy
    image: gitea/gitea:${gitea_version:-1.24}
    container_name: gitea
    restart: always
    depends_on:
      - giteadb
    environment:
      GITEA__server__ROOT_URL: https://git.${domain}/
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: giteadb:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${db_pass}
      GITEA__actions__ENABLED: true
      GITEA__server__DISABLE_SSH: true
    networks:
      proxy: null
      default: null
    volumes:
      - ${data:-.}/server:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitea.entryPoints: "https"
      traefik.http.routers.gitea.rule: "Host(`git.${domain}`)"
      traefik.http.services.gitea.loadbalancer.server.url: "http://gitea:3000"
  giteadb:
    <<: *logging-policy
    image: postgres:${postgres_version:-14}
    container_name: gitea_db
    restart: always
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: ${db_pass}
    networks:
      default: null
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
  runner:
    <<: *logging-policy
    image: gitea/act_runner:${runner_version:-nightly}
    container_name: gitea_runner
    restart: always
    depends_on:
      - gitea
    environment:
      GITEA_INSTANCE_URL: https://git.${domain}/
      GITEA_RUNNER_REGISTRATION_TOKEN: ${token}
      GITEA_RUNNER_NAME: gitea_runner
      GITEA_RUNNER_LABELS:
        "docker:docker://data.forgejo.org/oci/node:20-bullseye,\
        ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest,\
        ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04,\
        ubuntu-20.04:docker://docker.gitea.com/runner-images:ubuntu-20.04"
    networks:
      default: null
    volumes:
      - ${data:-.}/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
