networks:
  default: null
  proxy:
    external: true
x-common-settings: &common-settings
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
  security_opt:
    - no-new-privileges:true
  stdin_open: false
  tty: false
services:
  gitea:
    <<: *common-settings
    image: docker.gitea.com/gitea:${gitea_version:-1.25-rootless}
    container_name: gitea
    user: ${uid:-1000}:${gid:-1000}
    restart: unless-stopped
    cap_drop:
      - ALL
    depends_on:
      - giteadb
    environment:
      GITEA__server__ROOT_URL: https://git.${domain}/
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: giteadb:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: ${db_pass}
      GITEA__actions__ENABLED: true
      GITEA__server__DISABLE_SSH: true
    networks:
      proxy: null
      default: null
    volumes:
      - ${data:-.}/data:/var/lib/gitea:rw
      - ${data:-.}/config:/etc/gitea:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitea.entryPoints: "https"
      traefik.http.routers.gitea.rule: "Host(`git.${domain}`)"
      traefik.http.services.gitea.loadbalancer.server.url: "http://gitea:3000"
  giteadb:
    <<: *common-settings
    image: postgres:${postgres_version:-14}
    container_name: gitea_db
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: ${db_pass}
    networks:
      default: null
    volumes:
      - ${data:-.}/db:/var/lib/postgresql/data
  runner:
    <<: *common-settings
    image: gitea/act_runner:${runner_version:-nightly}
    container_name: gitea_runner
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    depends_on:
      - gitea
    environment:
      GITEA_INSTANCE_URL: https://git.${domain}/
      GITEA_RUNNER_REGISTRATION_TOKEN: ${token}
      GITEA_RUNNER_NAME: gitea_runner
      GITEA_RUNNER_LABELS:
        "docker:docker://data.forgejo.org/oci/node:20-bullseye,\
        ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest,\
        ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04,\
        ubuntu-20.04:docker://docker.gitea.com/runner-images:ubuntu-20.04"
    networks:
      default: null
    volumes:
      - ${data:-.}/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
