networks:
  proxy:
    external: true
x-logging-policy: &logging-policy
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
      compress: "true"
services:
  syncthing:
    <<: *logging-policy
    image: lscr.io/linuxserver/syncthing:${syncthing_version:-latest}
    container_name: syncthing
    restart: always
    network_mode: host
    environment:
      PUID: ${uid:-1000}
      PGID: ${gid:-1000}
      UMASK: ${umask:-0220}
    volumes:
      - ${syncthingFolder}/Syncthing:/data1:rw
      - ${data:-.}/sync:/config:rw
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.entryPoints: "https"
      traefik.http.routers.syncthing.middlewares: "localonly@file"
      traefik.http.routers.syncthing.rule: "Host(`sync.${domain}`)"
      traefik.http.routers.syncthing.tls.certresolver: "cloudflare"
      traefik.http.services.syncthing.loadbalancer.server.url: "http://${host_ip}:8384"
